apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-base-deployment
  labels:
    app: projeto-base
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projeto-base
  template:
    metadata:
      labels:
        app: projeto-base
    spec:
      containers:
        - name: projeto-base-container
          image: dvvdoficial/projeto-base:latest
          ports:
            - containerPort: 8080
